### ISSUE TITLE
Support "class properties"

### ISSUE THREAD

**Issue by wiredearp** [akira-cn/babel-plugin-transform-private#1]
:beer: Great plugin. Such awesome.

I will propose an enhancement to support "class properties" provided in Babel via https://www.npmjs.com/package/babel-plugin-transform-class-properties.

```javascript
class Example {
  _x = 0;
  _y = 0;
  right() {
    this._x += 1;
  }
  down() {
    this._y += 1;
  }
}
```

I've tried running `transform-private` both before and after `transform-class-properties` with the same result: The other plugin moves the property declarations into the `constructor`, but they are not translated into symbol properties by this plugin.

Interestingly, The class properties are correctly declared as symbols in the output, but I assume that this is just a lucky side effect of `babel-plugin-syntax-class-properties`. The output looks something like this:

```javascript
const Example = function() {
  const [$_x$, $_y$] = [Symbol('$_x$'), Symbol('$_y$')];
  let Example = class Example {
    constructor(...args) {
      return super(...args), this._x = 0, this._y = 0; // not symbols!
    }
  }
  return Example;
}()
```

This may not be easy to implement, but then again, perhaps it is?

**Comment by akira-cn** [comment]
I guess it's ok now. :-)

**Comment by wiredearp** [comment]
:tada: I ran the `0.1.3` release on pretty large codebase and it works :a: :ok: with no statistically significant performance cost! Thanks for the lightning fast update. I only ran into one issue which may not be valid, but perhaps interesting nonetheless.

```javascript
import Something from './somewhere';

// symbols work here (in closed scope)
export default class Point() {
  this[$_x$] = 0;
  this[$_y$] = 0;
  reset() {
    resetpoint(this);
  }
}

// but not here (out of scope)
function resetpoint(point) {
  point._x = 0;
  point._y = 0;
}
```

Since the `resetpoint` method is not exported out of the module, I had considered it "private" to the class in question and screened it safe to access private properties. I can see how a decorator might be a better example:

```javascript
export default class Point() {
  this[$_x$] = 0;
  this[$_y$] = 0;
  @requiresmoved reset() {
    this[$_x$] = 0;
    this[$_y$] = 0;
  }
  @requiresmoved revert() {
    this.reset();
  }
  @requiresmoved rollback() {
    this.revert();
  }
}

function requiresmoved(target, name, descriptor) {
  const base = descriptor.value;
  descriptor.value = function() {
    if(this._x === 0 && this._y === 0) { // not symbols!
      throw new Error('You must move it first!');
    } else {
      base();
    }
  };
  return descriptor;
}

```

And then of course it can be handy to declare old school functions outside of the generated scope for use in `array.map` and `filter` and `reduce` scenario (since instance methods don't compose so well). I suspect these examples do violate some fundamental principle of private instance members, but this principle seems to be at odds with "privacy in the module" somehow. Any attempt to address this hypothetical concern should of course involve declaring the symbols in the root of the module (somewhere next to the `import` statements) but there is of course a lot of questionable decisions involved in this. So anyways, thanks for the update!
